name: Sync to Hugging Face
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # REPLACE BELOW: Change 'YourUser/stremsrc' to your actual Hugging Face Space ID
        run: git push https://ameer0khan:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/ameer0khan/Stremsrc main
